wikidot_username = "Notifier"
config_wiki = "notifications"
user_config_category = "notify"
wiki_config_category = "wiki"
overrides_url = "https://notifications.wdfiles.com/local--code/overrides/1"
gmail_username = "wikidotnotifier@gmail.com"

[database]
driver = "notifier.database.drivers.mysql.MySqlDriver"
database_name = "wikidot_notifier"

[path]
# Paths:
# . -> cwd
# @ -> package root
# ? -> this config file
lang = "@/lang.toml"