name: tests
on:
  # Run on push to main
  push:
    paths:
      - 'notifier/**'
      - 'tests/**'
      - 'config/**'
      - 'pyproject.toml'
      - 'config/config.toml'
      - '.github/workflows/tests.yml'
    branches: [ main ]
    
  # Run on PR
  pull_request:
    paths:
      - 'notifier/**'
      - 'tests/**'
      - 'config/**'
      - 'pyproject.toml'
      - 'config/config.toml'
      - '.github/workflows/tests.yml'

  # Run manually
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run tests
        run: ./tests/run_tests.sh
